# Generated by Django 2.2.16 on 2022-08-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0002_auto_20220824_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
