# Generated by Django 2.2.16 on 2022-08-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0004_auto_20220824_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('pk',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('pk',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('pk',), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведение'},
        ),
    ]
