# Generated by Django 2.2.16 on 2022-08-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0008_auto_20220824_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведение'},
        ),
    ]
