# Generated by Django 2.2.16 on 2022-08-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0009_auto_20220824_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('pk',), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведение'},
        ),
    ]
