# Generated by Django 2.2.16 on 2022-08-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220825_2222'),
        ('reviews', '0004_remove_title_rating'),
    ]

    operations = [
    ]
