# Generated by Django 2.2.16 on 2022-08-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_title_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
