# Generated by Django 2.2.16 on 2022-08-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220827_1832'),
        ('reviews', '0007_remove_title_rating'),
    ]

    operations = [
    ]
